name = "naver-stock-screener"
main = "worker.js"
compatibility_date = "2026-07-01"

[[d1_databases]]
binding = "DB"
database_name = "여기에-D1-데이터베이스-이름"
database_id = "여기에-D1-데이터베이스-ID"

[triggers]
crons = ["*/10 0-6 * * 1-5"]
